version: '3.5'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:80"
    volumes:
      - blogfy_static_volume:/blogfy/static
      - blogfy_files_volume:/blogfy/files
    networks:
      - nginx_network

volumes:
  blogfy_static_volume:
    external: true
  blogfy_files_volume:
    external: true
networks:
  nginx_network:
    external: true



